# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98104c7e5b56c5264daef3de30a10ca6c0dc05a086c38a0b3c18beb4d2172e72bcb41abc958217db7c52193b4b25af2f6c903892f1198b517f92c597fe5e290a

test:
  secret_key_base: 1443d3f6092926cd2d60a069837fa93945b4f1ecc57568cec1c826f9af9cdeaf079069b1b32af57bcc6ae9579ddf8ddcdbd596fef2a11a272d55018074f0b12b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
